name: Publish VSCode Extension

on:
  release:
    types: [published]

jobs:
  publish:
    if: >-
      github.event.release && !github.event.release.draft && github.event.release.assets[0]
      && endsWith(github.event.release.assets[0].name, '.vsix')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ${{ github.repository }} ${{ github.ref_type }} ${{ github.ref_name }}
        uses: actions/checkout@v4

      - name: Setup node with cache
        uses: actions/setup-node@v3
        with:
          cache: npm

      - name: Download vsix file from release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo Downloadable at "${{ github.event.release.assets[0].browser_download_url }}"
          gh api -H "Accept: application/octet-stream" "${{ github.event.release.assets[0].url }}" \
          > "${{ github.event.release.assets[0].name }}"

      - name: List packaged files inside vsix
        run: unzip -l -vqq "${{ github.event.release.assets[0].name }}" | awk '{print $8}'

      - name: Publish to VSCode Extension Marketplace
        env:
          VSCE_PAT: ${{ secrets.VS_MARKETPLACE_TOKEN }}
        if: ${{ env.VSCE_PAT != '' }}
        run: |
          npm i -g vsce
          echo vsce $(vsce --version)
          vsce publish --packagePath "${{ github.event.release.assets[0].name }}"
